### ISSUE TITLE
stLFR_GapCloser: ../readtool/stLFRReadHeader.hpp:63: void stLFRHeader::Init(const string&): Assertion `items_2.size() == 2' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by xfcypeng** [BGI-Qingdao/stLFR_GapCloser#1]
stLFR_GapCloser: ../readtool/stLFRReadHeader.hpp:63: void stLFRHeader::Init(const string&): Assertion `items_2.size() == 2' failed.
Aborted (core dumped)

**Comment by cchd0001** [comment]
please provide the head 10 lines of your fastq

**Comment by jarojasva** [comment]
@M04874:18:000000000-D25J4:1:1101:15780:1330 1:N:0:2
AGACAATCCTTTGTAGCTTGGGCGTTATTCGATGCTTGACCTTTTCGCGTTGTGCATCCGCTGCACCGTGATCGATCTCGCTGCCTGGAGTGGGCAATCTCCCTATCGCTTGTGGCTCCCGGCCGGCGATCTTCGTCGCGGTCCGGCTGACCGGGGCCGAGAATGCCATTTGCCATGAATATTGCATGCCAGCACGGCAGATCCTGCCTGCCCGGC
+
BCDCDFFFFFFFGGGGGGGGGGHGGGGHHHHHHHGHHHHHHHHHHHGGGGGGGGHHHHHGGGGGHHHGHHGHHGGHHHHHGGGGHHHHHHHHGHGHGHHHHHHHHHHGGHHGHHGHHHGGGGGGGGGGGGGHHHHHGGGGGGGGGGGGGGHGGGGGGGGGFF?FFFFEFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFBFFFFFFFFFFEFFFFFF
@M04874:18:000000000-D25J4:1:1101:15965:1334 1:N:0:2
CAGCAGGCCATTGCCCTGCTGCAGCTTTCCACCCTCGACCTGCGCCAGGAAGTCCAGCAGGCCCTGGAATCCAACCCCATGCTGGAGCTCGACGAGGACTTCGGCGAGCTGGCGGTCGGCGAGACGGCCGAGGACGACTGGGCCAGCGAGATTCCCGATGAACTGACCGTCGACAGCGACTGGTCCGACACCTATCAGGACGCCGGCCTGGGAAGCCTGAGCGGCTCGGGCAGCGGCGAGGCCCCCGATTT
+
ACCC?FBCCCFFGGGGGGGGGGHHHHHHHHHHHGHHGGGGGHHGGGGGHHHHHHGHHHHHHGGGHHHHHHHHGHHGGGGHHHHHFFHHHHGGGGCGGFHHHHGGGGGGGGHHGGGGGGGGGCGGGGGGGCCFGFGGGGGGGGGGGGGF@BBFFFFFFDCFFFFFFFFFFFFF-CDFFFFABFFBBFFFA9BEFFFFBBFFFFFFFFFDF?EEAFDEFFFFFFADF-?-@DA-ADCFFA--@@ADFF=;-;E
@M04874:18:000000000-D25J4:1:1101:15654:1336 1:N:0:2
GGCCTGCATGGCGGAGGCTTCCGGCCAAGACCTGGATCAGTTCATGCTGTGGTACTCCCAGGCCGGCACGCCGGAAATC

**Comment by jarojasva** [comment]
I've got the same error:
stLFR_GapCloser: ../readtool/stLFRReadHeader.hpp:63: void stLFRHeader::Init(const string&): Assertion `items_2.size() == 2' failed.
Aborted (core dumped)

**Comment by cchd0001** [comment]
Hi,   

Your FASTQ files looks like raw stLFR fastq. please first split the barcode by https://github.com/BGI-Qingdao/stLFR_barcode_split
