### ISSUE TITLE
GapCloser

### ISSUE THREAD

**Issue by ad010902** [BGI-Qingdao/stLFR_GapCloser#2]
Hi,
I'm using GapClose, so can you show me  -b <string> input library info file name, required?

**Comment by cchd0001** [comment]
1st. prepare the lib.cfg The format comes from SOAPdenovo, see details from https://github.com/aquaskyline/SOAPdenovo2 . Here is a basic example:
```
#maximal read length
max_rd_len=100
[LIB]
#average insert size
avg_ins=300
#if sequence needs to be reversed
reverse_seq=0
#a pair of fastq files, read1 file should be followed by read2 file
q1=split_reads.1.fq.gz
q2=split_reads.2.fq.gz
```
2nd. run the program
YOUR-DOWNLOAD-DIR/Release/stLFR_GapCloser -a your-scaffold-file -b lib.cfg -o result.scaff
